//
// File generated by rootcint at Tue Nov 21 09:48:31 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME trigviewDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "trigviewDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Viewer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_Viewer(void *p);
   static void deleteArray_Viewer(void *p);
   static void destruct_Viewer(void *p);
   static void streamer_Viewer(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Viewer*)
   {
      ::Viewer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Viewer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Viewer", ::Viewer::Class_Version(), "./trigview.h", 15,
                  typeid(::Viewer), DefineBehavior(ptr, ptr),
                  &::Viewer::Dictionary, isa_proxy, 0,
                  sizeof(::Viewer) );
      instance.SetDelete(&delete_Viewer);
      instance.SetDeleteArray(&deleteArray_Viewer);
      instance.SetDestructor(&destruct_Viewer);
      instance.SetStreamerFunc(&streamer_Viewer);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Viewer*)
   {
      return GenerateInitInstanceLocal((::Viewer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Viewer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr Viewer::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Viewer::Class_Name()
{
   return "Viewer";
}

//______________________________________________________________________________
const char *Viewer::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Viewer::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Viewer::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Viewer::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void Viewer::Streamer(TBuffer &R__b)
{
   // Stream an object of class Viewer.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void Viewer::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Viewer.
      TClass *R__cl = ::Viewer::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCleanup", &fCleanup);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHScaleCanvas", &fHScaleCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVScaleCanvas", &fVScaleCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHScale", &fHScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVScale", &fVScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHSlider", &fHSlider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVSlider", &fVSlider);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "max_size", &max_size);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xbox1", &xbox1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ybox1", &ybox1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xbox2", &xbox2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ybox2", &ybox2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xbox1old", &xbox1old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ybox1old", &ybox1old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xbox2old", &xbox2old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ybox2old", &ybox2old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sxy", &sxy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x0", &x0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y0", &y0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fT0", &fT0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xmin_xmax", &xmin_xmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x1", &x1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y1", &y1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x2", &x2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y2", &y2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bcs_iw[1000000]", bcs_iw);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_Viewer(void *p) {
      delete ((::Viewer*)p);
   }
   static void deleteArray_Viewer(void *p) {
      delete [] ((::Viewer*)p);
   }
   static void destruct_Viewer(void *p) {
      typedef ::Viewer current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Viewer(TBuffer &buf, void *obj) {
      ((::Viewer*)obj)->::Viewer::Streamer(buf);
   }
} // end of namespace ROOT for class ::Viewer

/********************************************************
* trigviewDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabletrigviewDict();

extern "C" void G__set_cpp_environmenttrigviewDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("trigview.h");
  G__cpp_reset_tagtabletrigviewDict();
}
#include <new>
extern "C" int G__cpp_dllrevtrigviewDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Viewer */
static int G__trigviewDict_306_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Viewer* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Viewer((TGWindow*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) Viewer((TGWindow*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__trigviewDictLN_Viewer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->MousePosition((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TObject*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->DoButton();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((Viewer*) G__getstructoffset())->GetCanvas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ((Viewer*) G__getstructoffset())->SetRange((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])
, (Float_t) G__double(libp->para[2]), (Float_t) G__double(libp->para[3])
, (Bool_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((Viewer*) G__getstructoffset())->SetRange((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])
, (Float_t) G__double(libp->para[2]), (Float_t) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Viewer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Viewer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Viewer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Viewer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__trigviewDict_306_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Viewer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Viewer G__TViewer;
static int G__trigviewDict_306_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Viewer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Viewer*) (soff+(sizeof(Viewer)*i)))->~G__TViewer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Viewer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Viewer*) (soff))->~G__TViewer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Viewer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunctrigviewDict {
 public:
  G__Sizep2memfunctrigviewDict(): p(&G__Sizep2memfunctrigviewDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunctrigviewDict::*p)();
};

size_t G__get_sizep2memfunctrigviewDict()
{
  G__Sizep2memfunctrigviewDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancetrigviewDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__trigviewDictLN_Viewer))) {
     Viewer *G__Lderived;
     G__Lderived=(Viewer*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer),G__get_linked_tagnum(&G__trigviewDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabletrigviewDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__trigviewDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Viewer */
static void G__setup_memvarViewer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer));
   { Viewer *p; p=(Viewer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TList),-1,-1,4,"fCleanup=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TCanvas),-1,-1,4,"fCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TRootEmbeddedCanvas),-1,-1,4,"fHScaleCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TRootEmbeddedCanvas),-1,-1,4,"fVScaleCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TGaxis),-1,-1,4,"fHScale=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TGaxis),-1,-1,4,"fVScale=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TGDoubleSlider),-1,-1,4,"fHSlider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TGDoubleSlider),-1,-1,4,"fVSlider=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"max_size=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"xbox1=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ybox1=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"xbox2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ybox2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"xbox1old=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ybox1old=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"xbox2old=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ybox2old=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"sxy=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"x0=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"y0=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fT0=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"xmin_xmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"x1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"y1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"x2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"y2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"bcs_iw[1000000]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__trigviewDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvartrigviewDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncViewer(void) {
   /* Viewer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__trigviewDictLN_Viewer));
   G__memfunc_setup("Viewer",626,G__trigviewDict_306_0_1, 105, G__get_linked_tagnum(&G__trigviewDictLN_Viewer), -1, 0, 1, 1, 1, 0, "U 'TGWindow' - 10 - win", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MousePosition",1374,G__trigviewDict_306_0_2, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - event i - 'Int_t' 0 - x "
"i - 'Int_t' 0 - y U 'TObject' - 0 - selected", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoButton",815,G__trigviewDict_306_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCanvas",892,G__trigviewDict_306_0_4, 85, G__get_linked_tagnum(&G__trigviewDictLN_TCanvas), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRange",793,G__trigviewDict_306_0_5, 121, -1, -1, 0, 5, 1, 1, 0, 
"f - 'Float_t' 0 - xmin f - 'Float_t' 0 - ymin "
"f - 'Float_t' 0 - xmax f - 'Float_t' 0 - ymax "
"g - 'Bool_t' 0 'kTRUE' move_slider", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__trigviewDict_306_0_6, 85, G__get_linked_tagnum(&G__trigviewDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Viewer::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__trigviewDict_306_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Viewer::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__trigviewDict_306_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Viewer::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__trigviewDict_306_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Viewer::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__trigviewDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__trigviewDict_306_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__trigviewDict_306_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Viewer::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__trigviewDict_306_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Viewer::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__trigviewDict_306_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Viewer::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__trigviewDict_306_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Viewer::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Viewer", 752, G__trigviewDict_306_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunctrigviewDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaltrigviewDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_functrigviewDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__trigviewDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__trigviewDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGaxis = { "TGaxis" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_TGDoubleSlider = { "TGDoubleSlider" , 99 , -1 };
G__linked_taginfo G__trigviewDictLN_Viewer = { "Viewer" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabletrigviewDict() {
  G__trigviewDictLN_TClass.tagnum = -1 ;
  G__trigviewDictLN_TBuffer.tagnum = -1 ;
  G__trigviewDictLN_TMemberInspector.tagnum = -1 ;
  G__trigviewDictLN_TObject.tagnum = -1 ;
  G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__trigviewDictLN_TList.tagnum = -1 ;
  G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__trigviewDictLN_TGObject.tagnum = -1 ;
  G__trigviewDictLN_TQObject.tagnum = -1 ;
  G__trigviewDictLN_TGWindow.tagnum = -1 ;
  G__trigviewDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__trigviewDictLN_TGFrame.tagnum = -1 ;
  G__trigviewDictLN_TGCompositeFrame.tagnum = -1 ;
  G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__trigviewDictLN_TGMainFrame.tagnum = -1 ;
  G__trigviewDictLN_TCanvas.tagnum = -1 ;
  G__trigviewDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__trigviewDictLN_TGaxis.tagnum = -1 ;
  G__trigviewDictLN_TGDoubleSlider.tagnum = -1 ;
  G__trigviewDictLN_Viewer.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabletrigviewDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TList);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGaxis);
   G__get_linked_tagnum_fwd(&G__trigviewDictLN_TGDoubleSlider);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__trigviewDictLN_Viewer),sizeof(Viewer),-1,62464,"GUI example",G__setup_memvarViewer,G__setup_memfuncViewer);
}
extern "C" void G__cpp_setuptrigviewDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuptrigviewDict()");
  G__set_cpp_environmenttrigviewDict();
  G__cpp_setup_tagtabletrigviewDict();

  G__cpp_setup_inheritancetrigviewDict();

  G__cpp_setup_typetabletrigviewDict();

  G__cpp_setup_memvartrigviewDict();

  G__cpp_setup_memfunctrigviewDict();
  G__cpp_setup_globaltrigviewDict();
  G__cpp_setup_functrigviewDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunctrigviewDict();
  return;
}
class G__cpp_setup_inittrigviewDict {
  public:
    G__cpp_setup_inittrigviewDict() { G__add_setup_func("trigviewDict",(G__incsetup)(&G__cpp_setuptrigviewDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_inittrigviewDict() { G__remove_setup_func("trigviewDict"); }
};
G__cpp_setup_inittrigviewDict G__cpp_setup_initializertrigviewDict;

