/********************************************************************
* segmdictDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error segmdictDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablesegmdictDict();
extern void G__cpp_setup_inheritancesegmdictDict();
extern void G__cpp_setup_typetablesegmdictDict();
extern void G__cpp_setup_memvarsegmdictDict();
extern void G__cpp_setup_globalsegmdictDict();
extern void G__cpp_setup_memfuncsegmdictDict();
extern void G__cpp_setup_funcsegmdictDict();
extern void G__set_cpp_environmentsegmdictDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "segmdict.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__segmdictDictLN_TClass;
extern G__linked_taginfo G__segmdictDictLN_TBuffer;
extern G__linked_taginfo G__segmdictDictLN_TMemberInspector;
extern G__linked_taginfo G__segmdictDictLN_TObject;
extern G__linked_taginfo G__segmdictDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__segmdictDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__segmdictDictLN_TList;
extern G__linked_taginfo G__segmdictDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__segmdictDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__segmdictDictLN_TGObject;
extern G__linked_taginfo G__segmdictDictLN_TQObject;
extern G__linked_taginfo G__segmdictDictLN_TGWindow;
extern G__linked_taginfo G__segmdictDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__segmdictDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__segmdictDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__segmdictDictLN_TGFrame;
extern G__linked_taginfo G__segmdictDictLN_TGCompositeFrame;
extern G__linked_taginfo G__segmdictDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__segmdictDictLN_TGMainFrame;
extern G__linked_taginfo G__segmdictDictLN_TCanvas;
extern G__linked_taginfo G__segmdictDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__segmdictDictLN_TGaxis;
extern G__linked_taginfo G__segmdictDictLN_TGDoubleSlider;
extern G__linked_taginfo G__segmdictDictLN_Viewer;

/* STUB derived class for protected member access */
