/********************************************************************
* trigviewDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error trigviewDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabletrigviewDict();
extern void G__cpp_setup_inheritancetrigviewDict();
extern void G__cpp_setup_typetabletrigviewDict();
extern void G__cpp_setup_memvartrigviewDict();
extern void G__cpp_setup_globaltrigviewDict();
extern void G__cpp_setup_memfunctrigviewDict();
extern void G__cpp_setup_functrigviewDict();
extern void G__set_cpp_environmenttrigviewDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "trigview.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__trigviewDictLN_TClass;
extern G__linked_taginfo G__trigviewDictLN_TBuffer;
extern G__linked_taginfo G__trigviewDictLN_TMemberInspector;
extern G__linked_taginfo G__trigviewDictLN_TObject;
extern G__linked_taginfo G__trigviewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__trigviewDictLN_TList;
extern G__linked_taginfo G__trigviewDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__trigviewDictLN_TGObject;
extern G__linked_taginfo G__trigviewDictLN_TQObject;
extern G__linked_taginfo G__trigviewDictLN_TGWindow;
extern G__linked_taginfo G__trigviewDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__trigviewDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__trigviewDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__trigviewDictLN_TGFrame;
extern G__linked_taginfo G__trigviewDictLN_TGCompositeFrame;
extern G__linked_taginfo G__trigviewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__trigviewDictLN_TGMainFrame;
extern G__linked_taginfo G__trigviewDictLN_TCanvas;
extern G__linked_taginfo G__trigviewDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__trigviewDictLN_TGaxis;
extern G__linked_taginfo G__trigviewDictLN_TGDoubleSlider;
extern G__linked_taginfo G__trigviewDictLN_Viewer;

/* STUB derived class for protected member access */
