
/* roadfinder1.cc - finding roads using 'if' method; file 'cinclude/dcroadfinder.c' must be generated by 'dc_dict' */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

using namespace std;
#include <strstream>

#include "dclib.h"
#include "sgutil.h"

#define ROADS_SEARCH
//#include "dcroadfinder.h"



/*xc5vtx150tff1156-2 (SSP)*/
/* 3.48/3/1/%0/%0/%7/%30 - pipeline, 11K roads */

void
RoadSearch1(word112_t sl[6], ap_uint<1> res[112])
{
#pragma HLS ARRAY_PARTITION variable=sl complete dim=1
#pragma HLS ARRAY_PARTITION variable=res complete dim=1
#pragma HLS PIPELINE

  ROADS_SEARCH;

  return;
}
